module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_iframe: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  ds: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  fakeobjects: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  image: 0
  imce: 0
  kint: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  quickedit: 0
  search: 0
  styleguide: 0
  svg_image_field: 0
  system: 0
  taoti_helper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  taoti: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  sparkle_motion: 0
  westat: 0
profile: taoti
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
